defaults: &defaults
  aws_id: <%= ENV['AWS_ID'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  artist_auth_name: <%= ENV['ARTIST_AUTH_NAME'] %>
  artist_auth_pass: <%= ENV['ARTIST_AUTH_PASS'] %>
  asset_hash_secret: <%= ENV['ASSET_HASH_SECRET'] %>

development:
  <<: *defaults

test: &testing
  <<: *defaults

production: &production
  <<: *defaults
